spring:
  datasource:
    username: bocloud
    password: a@!#123
    url: jdbc:mysql://localhost1:3316/nacha_auth?characterEncoding=utf8&allowMultiQueries=true&&zeroDateTimeBehavior=convertToNull
  application:
    name: spring-cloud-database
server:
  port: 7003
