spring:
  jackson:
    deserialization:
      FAIL_ON_NULL_CREATOR_PROPERTIES: true
  resources:
    # 可以直接访问static下的静态资源，http://localhost:8080/image.html
    # 最好有个子目录，放行子目录，否则可以直接获取application.yml配置文件
    static-locations: classpath:static/,file:static/
  servlet:
    multipart:
      max-file-size: 10KB